#  __      __        _         _____          _ _             
#  \ \    / /       (_)       / ____|        | (_)            
#   \ \  / /__ _ __  ___  __ | |     ___   __| |_ _ __   __ _ 
#    \ \/ / _ \ '_ \| \ \/ / | |    / _ \ / _` | | '_ \ / _` |
#     \  /  __/ | | | |>  <  | |___| (_) | (_| | | | | | (_| |
#      \/ \___|_| |_|_/_/\_\  \_____\___/ \__,_|_|_| |_|\__, |
#                                                        __/ |
#                                                       |___/ 


support: "https://discord.gg/qFh2jmezCm"

# default speed: 1.0
FastRod:
  speed: 1.0
  sound: true